name: synergetics_manager
description: "A Flutter mobile app for manager KYC onboarding and business management."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  
  # Navigation
  go_router: ^16.0.0
  
  # Backend Integration
  supabase_flutter: ^2.9.1
  
  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # UI Components
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.0.0
  
  # Utilities
  shared_preferences: ^2.5.3
  equatable: ^2.0.5
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^3.2.0
  json_serializable: ^6.8.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
